
trigger:
- development

pool:
  vmImage: 'windows-latest'

variables:
  fileName: 'test.txt' # Variable name of first file
  filePath: '$(Build.ArtifactStagingDirectory)/$(fileName)' # Variable for path to first file
  secondfilePath: 'test2.txt'
  newFileName: 'new.txt' # Variable name of second file
  newFilePath: '$(Build.ArtifactStagingDirectory)/$(newFileName)' # Variable for path to second file

stages:
- stage: Write_Publish
  jobs:
  - job: Write
    steps:
    - powershell: | 
        Get-Date | Out-File -FilePath $(filePath) -Encoding utf8
        Set-Content -FilePath $(secondfilePath) -Value "asdfghjk"
      displayName: 'Write to file'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'first'
        publishLocation: 'Container'

- stage: Read_Copy
  dependsOn: Write_Publish
  jobs:
  - job: Read 
    strategy:
      parallel: 1
    steps:
      - task: DownloadBuildArtifacts@0 
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'first' 
          downloadPath: '$(System.ArtifactsDirectory)'

      - powershell: |
          Get-Content -Path $(System.ArtifactsDirectory)/test/$(fileName) | Write-Host
        displayName: 'Read from file'

  - job: Copy
    strategy:
      parallel: 1
    steps: 
    - task: DownloadBuildArtifacts@0 
      inputs:
        buildType: 'current'
        downloadType: 'single' 
        artifactName: 'first'
        downloadPath: '$(System.SourceDirectory)' 

    - powershell: | 
        $content = Get-Content -Path $(System.SourceDirectory)/first/$(fileName)
        Write-Host $content

        for ($i = 0; $i -lt 5; $i++) {
          Add-Content -Path $(newFilePath) -Value $content
            Start-Sleep -Seconds 1
        }
      displayName: 'Copy file'

    - task: PublishBuildArtifacts@1 
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        ArtifactName: 'second'
        publishLocation: 'Container' 
